# Generated by Django 4.0.2 on 2022-05-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Following',
        ),
    ]
