# Generated by Django 4.0.2 on 2022-02-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
